spring.application.name=Marketplace

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled = false
springdoc.swagger-ui.filter = false
springdoc.swagger-ui.syntaxHighlight.activated = true


spring.datasource.url = jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username = postgres
spring.datasource.password = 123456789
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.messages.basename=messages
spring.messages.encoding=UTF-8

api.fakeapi.platzi.url = https://api.escuelajs.co/api/v1/products

api.fakeapi.fakestore.url = https://fakestoreapi.com/products

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true

# Formatear las consultas SQL para que sean legibles
spring.jpa.properties.hibernate.format_sql=true
